const DB_KEY='colorpro.v06';
const defaultState={clients:[],diagnoses:[],simulations:[],formulas:[],settings:{unit:'g'}};
let state=load();
const levels=[1,2,3,4,5,6,7,8,9,10];
const backgrounds={1:'Negro',2:'Castaño muy oscuro',3:'Castaño oscuro',4:'Castaño medio',5:'Castaño claro',6:'Rubio oscuro',7:'Rubio',8:'Rubio claro',9:'Rubio muy claro',10:'Rubio extra claro'};
const reflections=['Natural','Ceniza','Irisado','Dorado','Cobrizo','Rojo','Violeta','Mate','Beige'];
const complements={Ceniza:'Naranja',Irisado:'Amarillo',Dorado:'Violeta',Cobrizo:'Azul',Rojo:'Verde',Violeta:'Amarillo',Mate:'Rojo'};
const views={dashboard:'Inicio',diagnosis:'Analizar cabello',target:'Color deseado',mixer:'Mezclador',simulator:'Simulador',calculators:'Calculadoras',clients:'Clientes',history:'Historial',brands:'Marcas',settings:'Ajustes'};
let currentView='dashboard';
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(DB_KEY)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(DB_KEY,JSON.stringify(state))}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){document.querySelector('#view-title').textContent=views[currentView];document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));document.querySelector('#content').innerHTML=pages[currentView]();bind();}
const pages={
dashboard:()=>`<div class="grid grid-4"><div class="panel stat"><span class="label">Clientes</span><div class="value">${state.clients.length}</div><span class="hint">Fichas guardadas localmente</span></div><div class="panel stat"><span class="label">Diagnósticos</span><div class="value">${state.diagnoses.length}</div><span class="hint">Evaluaciones registradas</span></div><div class="panel stat"><span class="label">Simulaciones</span><div class="value">${state.simulations.length}</div><span class="hint">Predicciones realizadas</span></div><div class="panel stat"><span class="label">Fórmulas</span><div class="value">${state.formulas.length}</div><span class="hint">Mezclas guardadas</span></div></div><div class="grid grid-2" style="margin-top:16px"><div class="panel"><div class="section-head"><div><h2>Flujo profesional</h2><p>De la consulta al resultado real</p></div></div><div class="steps">${['Cliente','Diagnóstico','Objetivo','Simulación','Fórmula','Resultado'].map((x,i)=>`<div class="step"><b>${i+1}</b>${x}</div>`).join('')}</div><div style="margin-top:18px"><div class="bar"><i style="width:${Math.min(100,state.clients.length?65:15)}%"></i></div></div></div><div class="panel"><div class="section-head"><div><h2>Acciones rápidas</h2><p>Empieza una nueva consulta</p></div></div><div class="quick"><button data-go="diagnosis"><strong>Analizar cabello</strong><span>Base, fondo e historial</span></button><button data-go="simulator"><strong>Simular resultado</strong><span>Predicción y confianza</span></button><button data-go="mixer"><strong>Crear fórmula</strong><span>Gramos y proporciones</span></button><button data-go="calculators"><strong>Calculadoras</strong><span>Oxidante y cantidades</span></button></div></div></div><div class="panel" style="margin-top:16px"><div class="section-head"><div><h2>Principio de trabajo</h2><p>La predicción orienta la decisión; no sustituye el diagnóstico profesional.</p></div></div><div class="notice">ColorPro separa nivel, fondo residual, reflejo, historia química y estado de la fibra. Cuando faltan datos o existe pigmento artificial, la confianza baja y el sistema evita presentar una fórmula como garantía.</div></div>`,
diagnosis:()=>`<div class="grid grid-2"><div class="panel"><h2>Diagnóstico capilar</h2><p class="muted">Registra lo que sabes antes de calcular.</p><form id="diagnosis-form"><div class="form-grid"><label>Cliente<select name="client"><option value="">Sin asignar</option>${state.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Estado de fibra<select name="fiber"><option>Normal</option><option>Porosa</option><option>Muy porosa</option><option>Sensible</option></select></label><label>Historia química<select name="history"><option>Virgen</option><option>Coloración permanente</option><option>Coloración demi</option><option>Decoloración</option><option>Alisado/permanente</option><option>Desconocida</option></select></label><label>Canas aproximadas<select name="gray"><option>0%</option><option>1–25%</option><option>26–50%</option><option>51–75%</option><option>76–100%</option></select></label></div><label style="margin-top:14px">Nivel actual<div class="level-row">${levels.map(n=>`<button type="button" class="level" data-level="${n}">${n}<small>${backgrounds[n].split(' ')[0]}</small></button>`).join('')}</div></label><label style="margin-top:14px">Observaciones<textarea name="notes" rows="4" placeholder="Bandas, zonas, reflejo visible, tratamientos, porosidad..."></textarea></label><div class="form-actions"><button class="primary">Guardar diagnóstico</button></div></form></div><div class="panel"><h2>Lectura técnica</h2><p class="muted">La base determina el punto de partida, pero no toda la historia del cabello.</p><div id="diagnosis-readout" class="result" style="margin-top:18px"><div class="big-result">Selecciona un nivel</div><p class="muted">Se mostrará el fondo conceptual asociado y los factores que pueden reducir la confianza.</p></div></div></div>`,
target:()=>`<div class="grid grid-2"><div class="panel"><h2>Color deseado</h2><p class="muted">Define nivel y familia de reflejo.</p><form id="target-form"><div class="form-grid"><label>Nivel objetivo<select name="level">${levels.map(n=>`<option value="${n}">${n} — ${backgrounds[n]}</option>`).join('')}</select></label><label>Reflejo<select name="reflection">${reflections.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Marca / línea<input name="brand" placeholder="Opcional"></label><label>Matiz comercial<input name="shade" placeholder="Ej. 8.1"></label></div><div class="form-actions"><button class="primary">Guardar objetivo</button></div></form></div><div class="panel"><h2>Familias de neutralización</h2><p class="muted">Relaciones conceptuales, independientes del código comercial.</p>${reflections.map(r=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid var(--line);font-size:12px"><span>${r}</span><span class="chip">${complements[r]||'—'}</span></div>`).join('')}</div></div>`,
mixer:()=>`<div class="grid grid-2"><div class="panel"><h2>Mezclador de fórmula</h2><p class="muted">Construye una mezcla por peso y proporción.</p><form id="mixer-form"><div id="mix-items"><div class="form-grid mix-row" style="margin-bottom:9px"><input name="shade" placeholder="Tono / producto"><input name="grams" type="number" min="0" step="0.1" value="30" placeholder="g"></div></div><button type="button" class="secondary" id="add-mix">+ Añadir producto</button><div class="form-actions"><button class="primary">Guardar fórmula</button></div></form></div><div class="panel"><h2>Resumen de mezcla</h2><div id="mix-summary"><div class="big-result">30 g</div><p class="muted">Añade componentes para calcular proporciones.</p></div></div></div>`,
simulator:()=>`<div class="grid grid-2"><div class="panel"><h2>Simulador probabilístico</h2><p class="muted">No devuelve una garantía; devuelve una hipótesis con factores de confianza.</p><form id="sim-form"><div class="form-grid"><label>Nivel actual<select name="current">${levels.map(n=>`<option value="${n}">${n} — ${backgrounds[n]}</option>`).join('')}</select></label><label>Nivel objetivo<select name="target">${levels.map(n=>`<option value="${n}">${n} — ${backgrounds[n]}</option>`).join('')}</select></label><label>Reflejo objetivo<select name="reflection">${reflections.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Historia química<select name="history"><option>Virgen</option><option>Coloración permanente</option><option>Decoloración</option><option>Desconocida</option></select></label></div><div class="form-actions"><button class="primary">Calcular predicción</button></div></form></div><div class="panel"><h2>Predicción</h2><div id="prediction" class="empty">Completa los datos y calcula.</div></div></div>`,
calculators:()=>`<div class="grid grid-3"><div class="panel"><h2>Mezcla 1:1</h2><p class="muted">Calcula oxidante sobre cantidad de color.</p><label>Color (g)<input id="calc-color" type="number" value="60" min="0"></label><label style="margin-top:10px">Proporción<select id="calc-ratio"><option value="1">1:1</option><option value="1.5">1:1.5</option><option value="2">1:2</option></select></label><div class="big-result" id="calc-oxidant" style="margin-top:16px">60 g</div></div><div class="panel"><h2>Oxidante orientativo</h2><p class="muted">La selección depende de marca, técnica, fibra y objetivo.</p><label>Nivel a subir<input id="calc-lift" type="number" value="2" min="0" max="5"></label><div id="lift-note" class="notice" style="margin-top:15px">2 niveles: requiere validar producto y técnica.</div></div><div class="panel"><h2>Cantidad de aplicación</h2><p class="muted">Estimación simple para planificación.</p><label>Largo<select id="calc-length"><option value="1">Corto</option><option value="1.4">Medio</option><option value="1.9">Largo</option></select></label><label style="margin-top:10px">Densidad<select id="calc-density"><option value="1">Normal</option><option value="1.3">Alta</option></select></label><div class="big-result" id="calc-quantity" style="margin-top:16px">60 g</div></div></div>`,
clients:()=>`<div class="panel"><div class="section-head"><div><h2>Clientes</h2><p>Historial preparado para comparar predicción y resultado real.</p></div><button class="primary" id="new-client-2">+ Nuevo cliente</button></div>${state.clients.length?`<table class="table"><thead><tr><th>Cliente</th><th>Diagnósticos</th><th>Simulaciones</th><th></th></tr></thead><tbody>${state.clients.map(c=>`<tr><td><strong>${esc(c.name)}</strong><br><span class="muted">${esc(c.notes||'')}</span></td><td>${state.diagnoses.filter(d=>d.client===c.id).length}</td><td>${state.simulations.filter(s=>s.client===c.id).length}</td><td><button class="danger" data-delete-client="${c.id}">Eliminar</button></td></tr>`).join('')}</tbody></table>`:`<div class="empty">Todavía no hay clientes. Crea la primera ficha para activar el flujo completo.</div>`}</div>`,
history:()=>`<div class="panel"><div class="section-head"><div><h2>Historial de simulaciones</h2><p>Registro de predicción, confianza y resultado esperado.</p></div></div>${state.simulations.length?`<table class="table"><thead><tr><th>Fecha</th><th>Base</th><th>Objetivo</th><th>Predicción</th><th>Confianza</th></tr></thead><tbody>${state.simulations.slice().reverse().map(s=>`<tr><td>${new Date(s.date).toLocaleDateString('es-ES')}</td><td>${s.current}</td><td>${s.target} ${esc(s.reflection)}</td><td>${s.predicted}</td><td><span class="confidence ${s.confidence.toLowerCase()}">${s.confidence}</span></td></tr>`).join('')}</tbody></table>`:`<div class="empty">No hay simulaciones todavía.</div>`}</div>`,
brands:()=>`<div class="grid grid-3"><div class="panel"><h2>Estructura universal</h2><p class="muted">Nivel 1–10, fondos, pigmentos y reflejos se mantienen separados del código comercial.</p>${levels.map(n=>`<span class="chip">${n} · ${backgrounds[n]}</span>`).join('')}</div><div class="panel"><h2>Productos</h2><p class="muted">El catálogo comercial se añadirá como datos, no como reglas incrustadas en la interfaz.</p><div class="notice">La fórmula final debe respetar instrucciones y proporciones de cada fabricante.</div></div><div class="panel"><h2>Reglas</h2><p class="muted">Neutralización, corrección y viabilidad se modelan como reglas consultables.</p><span class="chip">Viabilidad</span><span class="chip">Neutralización</span><span class="chip">Corrección</span></div></div>`,
settings:()=>`<div class="grid grid-2"><div class="panel"><h2>Ajustes</h2><label>Unidad de peso<select id="unit"><option ${state.settings.unit==='g'?'selected':''}>g</option><option ${state.settings.unit==='oz'?'selected':''}>oz</option></select></label><div class="form-actions"><button class="danger" id="clear-data">Borrar datos locales</button></div></div><div class="panel"><h2>Arquitectura</h2><p class="muted">Colorimetría + Diagnóstico + Productos → Simulador → Fórmula/Proceso → Resultado → Historial.</p><div class="notice">El núcleo funciona con datos locales. La foto puede servir como apoyo visual, pero no determina por sí sola la historia química ni sustituye el diagnóstico.</div></div></div>`};
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{currentView=b.dataset.go;render()});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()});const nf=document.querySelector('#new-client');if(nf)nf.onclick=openClient;const nf2=document.querySelector('#new-client-2');if(nf2)nf2.onclick=openClient;
const cf=document.querySelector('#client-form');if(cf)cf.onsubmit=e=>{e.preventDefault();const fd=new FormData(cf);state.clients.push({id:crypto.randomUUID(),name:fd.get('name'),notes:fd.get('notes'),created:new Date().toISOString()});save();cf.closest('dialog').close();toast('Cliente guardado');render()};
document.querySelectorAll('[data-delete-client]').forEach(b=>b.onclick=()=>{state.clients=state.clients.filter(c=>c.id!==b.dataset.deleteClient);save();render();toast('Cliente eliminado')});
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const r=document.querySelector('#diagnosis-readout');if(r)r.innerHTML=`<div class="big-result">Nivel ${b.dataset.level}</div><p>${backgrounds[b.dataset.level]}</p><span class="confidence medium">Confianza pendiente</span>`});
const df=document.querySelector('#diagnosis-form');if(df)df.onsubmit=e=>{e.preventDefault();const fd=new FormData(df), selected=df.querySelector('.level.selected')?.dataset.level;if(!selected){toast('Selecciona el nivel actual');return}state.diagnoses.push({id:crypto.randomUUID(),client:fd.get('client'),level:+selected,fiber:fd.get('fiber'),history:fd.get('history'),gray:fd.get('gray'),notes:fd.get('notes'),date:new Date().toISOString()});save();toast('Diagnóstico guardado')};
const tf=document.querySelector('#target-form');if(tf)tf.onsubmit=e=>{e.preventDefault();toast('Objetivo guardado para la siguiente simulación')};
const sf=document.querySelector('#sim-form');if(sf)sf.onsubmit=e=>{e.preventDefault();const fd=new FormData(sf),c=+fd.get('current'),t=+fd.get('target'),history=fd.get('history');const delta=t-c;let confidence='High',warnings=[];if(history==='Desconocida'){confidence='Low';warnings.push('historia química desconocida')}if(history==='Coloración permanente'&&delta>0){confidence='Low';warnings.push('el color artificial no se aclara de forma fiable con otro color')}if(history==='Decoloración'&&delta>2){confidence='Medium';warnings.push('fibra previamente decolorada')};if(delta>3){confidence='Low';warnings.push('salto de nivel elevado')}if(delta<0){warnings.push('objetivo más oscuro: considerar depósito y saturación')};const predicted=Math.max(1,Math.min(10,t+(history==='Desconocida'?0:0)));const s={id:crypto.randomUUID(),current:c,target:t,reflection:fd.get('reflection'),history,predicted,date:new Date().toISOString(),confidence,client:''};state.simulations.push(s);save();document.querySelector('#prediction').innerHTML=`<div class="result"><span class="confidence ${confidence.toLowerCase()}">${confidence}</span><div class="big-result" style="margin-top:10px">Nivel estimado ${predicted}</div><p>Tendencia: ${esc(fd.get('reflection'))}. Fondo residual: ${t>=8?'amarillo a amarillo pálido':t>=6?'amarillo/naranja':'rojo a naranja'}.</p>${warnings.length?`<div class="notice">${warnings.map(esc).join(' · ')}.</div>`:'<p class="muted">No se detectaron factores críticos con los datos aportados.</p>'}<p class="muted">Predicción orientativa; validar con diagnóstico, producto y prueba de mechón cuando corresponda.</p></div>`};
const af=document.querySelector('#add-mix');if(af)af.onclick=()=>{const wrap=document.querySelector('#mix-items');wrap.insertAdjacentHTML('beforeend','<div class="form-grid mix-row" style="margin-bottom:9px"><input name="shade" placeholder="Tono / producto"><input name="grams" type="number" min="0" step="0.1" value="20" placeholder="g"></div>');updateMix()};document.querySelectorAll('#mix-items input').forEach(i=>i.oninput=updateMix);const mf=document.querySelector('#mixer-form');if(mf)mf.onsubmit=e=>{e.preventDefault();const rows=[...document.querySelectorAll('.mix-row')].map(r=>({shade:r.querySelector('[name=shade]').value,grams:+r.querySelector('[name=grams]').value||0})).filter(x=>x.shade||x.grams);state.formulas.push({id:crypto.randomUUID(),items:rows,date:new Date().toISOString()});save();toast('Fórmula guardada')};
['calc-color','calc-ratio'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',calc));document.querySelector('#calc-lift')?.addEventListener('input',calc);['calc-length','calc-density'].forEach(id=>document.querySelector('#'+id)?.addEventListener('change',calc));document.querySelector('#unit')?.addEventListener('change',e=>{state.settings.unit=e.target.value;save();toast('Ajuste guardado')});document.querySelector('#clear-data')?.addEventListener('click',()=>{if(confirm('¿Borrar todos los datos locales?')){state={...defaultState,clients:[],diagnoses:[],simulations:[],formulas:[]};save();render();toast('Datos borrados')}});}
function openClient(){document.querySelector('#client-dialog').showModal()}
function updateMix(){const rows=[...document.querySelectorAll('.mix-row')],items=rows.map(r=>+r.querySelector('[name=grams]').value||0),total=items.reduce((a,b)=>a+b,0);document.querySelector('#mix-summary')&&(document.querySelector('#mix-summary').innerHTML=`<div class="big-result">${total.toFixed(1)} g</div><p class="muted">${rows.map((r,i)=>`${esc(r.querySelector('[name=shade]').value||'Producto')} · ${total?Math.round(items[i]/total*100):0}%`).join('<br>')}</p>`) }
function calc(){const c=+(document.querySelector('#calc-color')?.value||60),ratio=+(document.querySelector('#calc-ratio')?.value||1);const o=document.querySelector('#calc-oxidant');if(o)o.textContent=`${(c*ratio).toFixed(1)} g`;const lift=+(document.querySelector('#calc-lift')?.value||2);const n=document.querySelector('#lift-note');if(n)n.textContent=lift<=1?'1 nivel: validar técnica y producto.':lift<=2?'2 niveles: requiere validar producto y técnica.':'Más de 2 niveles: considerar estrategia de aclaración y diagnóstico profesional.';const l=+(document.querySelector('#calc-length')?.value||1),d=+(document.querySelector('#calc-density')?.value||1),q=document.querySelector('#calc-quantity');if(q)q.textContent=`${(60*l*d).toFixed(0)} g`}
render();
